### ISSUE TITLE
qry not resetting for new calls to search

### ISSUE THREAD

**Issue by PeterSmyth12** [gitronald/WebSearcher#3]
Running the following once 

```python
import WebSearcher as ws
se = ws.SearchEngine()
```
and this section  several (5) times, it appears that the qry parameter value is extended
```python
se.search('trump')
se.parse_results()
print(len(se.results))
se.results[0]
```
the output shows

{'type': 'general',
 'sub_rank': 0,
 'title': 'The Prophecies of Q - The Atlantic',
 'url': 'https://www.theatlantic.com/magazine/archive/2020/06/qanon-nothing-can-stop-what-is-coming/610567/',
 'cite': 'www.theatlantic.com › magazine › archive › 2020/06',
 'details': '',
 'text': 'You know that the mainstream media are their handmaidens, in partnership with Hillary Clinton and the secretive denizens of the deep state. You\xa0...',
 'timestamp': '13 May 2020',
 'cmpt_rank': 0,
 **'qry': 'trump?q=trump?q=trump?q=trump?q=trump',**
 'lang': 'en-GB',
 'serp_id': 'be2b1bb7a8657d73bd9a48209b3f5bd1a75823b565e1584f451c05ed',
 'serp_rank': 0}

**Comment by gitronald** [comment]
Thanks for catching this, I was always regenerating the `se` object so wasn't seeing that come up. Fixed and pushing changes now.
