### ISSUE TITLE
Searching for 'Zhiend' returns none

### ISSUE THREAD

**Issue by KuroChu** [gitronald/WebSearcher#47]
Think the title says it all.
Really surprising behavior.
```
import WebSearcher as ws
se = ws.SearchEngine()
se.search('Zhiend')
se.parse_results()
print(se.results[6])
```
This snipped would respond with
```
{'type': 'unknown', 'sub_type': None, 'sub_rank': 0, 'title': None, 'url': None, 'text': None, 'cite': None, 'details': None, 'cmpt_rank': 6, 'serp_rank': 6, 'serp_id': '...134b'}
```
So I thought it might be something to do with the character count. Nope.
You can search for words that are shorter than that, and it will give you the corresponding results.
Don't know why that is.

**Comment by gitronald** [comment]
Sorry for the delay, latest version (0.3.10) returns a mostly parsed page for that query. It's not parsing the knowledge component for that band (1st result) or the next component that contains a list of their songs. Updating the parsers for those components isn't a big priority for me at the moment but if you want to give it a shot please do!
